name: Greetings

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Greet on first issue
        if: github.event_name == 'issues' && github.event.action == 'opened' && github.event.sender.type == 'User'
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "👋 Welcome! Thank you for opening your first issue. We'll get back to you shortly."
          pr-message: ""
      
      - name: Greet on first pull request
        if: github.event_name == 'pull_request_target' && github.event.action == 'opened' && github.event.sender.type == 'User'
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: ""
          pr-message: "🎉 Congratulations on your first pull request! We appreciate your contribution."
